### ISSUE TITLE
Bug + Fix - An error occurred. Aborting : 'utf-8' codec can't decode byte 0xbe in position 2: invalid start byte

### ISSUE THREAD

**Issue by ventz** [mikechambers/digest#4]
When trying to run:
`python3 digest.py --output-dir ~/tmp/economist/ --cookie-source chrome`

got:

```
An error occurred. Aborting : 'utf-8' codec can't decode byte 0xbe in position 2: invalid start byte
Traceback (most recent call last):
  File "/private/tmp/b/digest-main/src/digest.py", line 827, in <module>
    main()
  File "/private/tmp/b/digest-main/src/digest.py", line 114, in main
    init_session()
  File "/private/tmp/b/digest-main/src/digest.py", line 689, in init_session
    cookies = get_browser_cookies(cookie_source)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/b/digest-main/src/digest.py", line 710, in get_browser_cookies
    return browsercookie.chrome()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/b/digest-main/.venv/lib/python3.11/site-packages/browsercookie/__init__.py", line 542, in chrome
    return Chrome(cookie_files).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/b/digest-main/.venv/lib/python3.11/site-packages/browsercookie/__init__.py", line 99, in load
    for cookie in sorted(self.get_cookies(), key=lambda cookie: cookie.expires):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/b/digest-main/.venv/lib/python3.11/site-packages/browsercookie/__init__.py", line 168, in get_cookies
    value = self._decrypt(item[5], item[6], item[4], item[1], key=key)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/b/digest-main/.venv/lib/python3.11/site-packages/browsercookie/__init__.py", line 195, in _decrypt
    return clean(decrypted)
           ^^^^^^^^^^^^^^^^
  File "/private/tmp/b/digest-main/.venv/lib/python3.11/site-packages/browsercookie/__init__.py", line 188, in clean
    return x[:-last].decode('utf8')
           ^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 2: invalid start byte
```

I was able to fix it by modify the `get_browser_cookies(...)` as:

```
def get_browser_cookies(browser_name):
    try:
        if browser_name.lower() == 'chrome':
            return browsercookie.chrome()
        elif browser_name.lower() == 'firefox':
            return browsercookie.firefox()
        elif browser_name.lower() == 'edge':
            return browsercookie.edge()
        elif browser_name.lower() == 'opera':
            return browsercookie.opera()
        else:
            raise ValueError("Unsupported --cookie-source name. Supported browsers: 'chrome', 'firefox', 'edge', 'opera'.")
    except UnicodeDecodeError as e:
        print(f"Error decoding cookies: {e}")
        print("Attempting fallback for problematic cookie values.")
        # Return an empty cookie jar or handle t he issue as needed
        return requests.cookies.RequestsCookieJar()
```

The real issue is in the `browsercookie` python module, but this at least lets you skip the non-properly decoded cookies.

By the way -- very nice project! Thanks for putting this together!

**Comment by ventz** [comment]
Not sure if something has changed with Chrome, but it seems that this is not working for authentication.

I am going to try to re-write the requests portion to playwright.

**Comment by mikechambers** [comment]
When you return an empty cookie jar, what happens? i.e. it doesnt crash, but you wont be able to authenticate with The Economist. Im guessing it will then create the digest based on the previews The Economist gives for unathenticated views.

Is that right?

**Comment by ventz** [comment]
@mikechambers Yes -- I was hoping to just skip the cookies that "did not work" essentially.

By the way, I re-wrote this using Playwright and a really elegant authentication. It seems much faster with Playwright too.
I also added PDF generation and a book preview, so you can generate a magazine essentially.

Just cleaning it up and will upload.

**Comment by mikechambers** [comment]
Playright is a browser automation library? So it still requires that there is a browers on the machine?

What I would love is to be able to authenticate with out having to have a browser install, so then you could run digest on a server and not have to manually run every week.

If you push can you do it as a branch?

**Comment by ventz** [comment]
> What I would love is to be able to authenticate with out having to have a browser install, so then you could run digest on a server and not have to manually run every week.

This is exactly what I wanted too! I was hoping to have a lambda generate it and create a web view thats like a magazine so I can read it easily/quickly every week.

There is a way to "record" the auth session which translates it into steps/automation for the login.
I did previously find a way to run Playwright into an AWS Lambda (this was shockingly difficult to do well), so I think the whole thing is doable.

I removed podcasts when I re-wrote this (only because I was hoping for that PDF book output), and I was going to create a dedicate github repo with the whole thing.
